# generated: '2026-06-20'
# method: generated
# source: openapi/tsg_mail_settings_v3.yaml
overlay: 1.0.0
info:
  title: API Evangelist enhancements for Twilio SendGrid Mail Settings API
  version: 1.0.0
extends: openapi/tsg_mail_settings_v3.yaml
actions:
- target: $.info
  update:
    x-apievangelist-provider: sendgrid
    x-apievangelist-index: https://raw.githubusercontent.com/api-evangelist/sendgrid/refs/heads/main/apis.yml
    x-apievangelist-enriched: '2026-06-20'
    x-apievangelist-operation-count: 13
